# Generated by Django 3.2.9 on 2021-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_csv_read_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_read',
            name='img',
            field=models.ImageField(null=True, upload_to='csv'),
        ),
    ]
