# Generated by Django 3.2.9 on 2021-12-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_csv_read_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_read',
            name='img',
        ),
    ]
