# Generated by Django 3.2.9 on 2021-12-07 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_csv_read_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_read',
            name='file',
            field=models.FileField(upload_to='csv', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
