# Generated by Django 3.2.9 on 2021-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='detail_URL',
            field=models.URLField(default=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='URL',
            field=models.URLField(default=True),
        ),
    ]
