# Generated by Django 3.2.9 on 2021-11-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211125_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='URL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='detail_URL',
            field=models.URLField(),
        ),
    ]
