# Generated by Django 3.2.9 on 2021-11-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211125_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='detail_URL',
        ),
    ]
