# Generated by Django 3.2.9 on 2021-12-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_work_detail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tool', to='portfolio.work'),
        ),
    ]
